#!/bin/bash

mysql -uroot -p$MYSQL_ROOT_PASSWORD <<EOF

  # create users
  CREATE USER '${BACKEND_DB_USER}'@'%' IDENTIFIED BY '${BACKEND_DB_PASS}';
  CREATE USER '${KEYCLOAK_DB_USER}'@'%' IDENTIFIED BY '${KEYCLOAK_DB_PASS}';

  # create databases
  CREATE DATABASE IF NOT EXISTS ${BACKEND_DB_NAME};
  CREATE DATABASE IF NOT EXISTS ${KEYCLOAK_DB_NAME};

  # add grants for users to databases
  GRANT ALL PRIVILEGES ON ${BACKEND_DB_NAME}.* TO '${BACKEND_DB_USER}'@'%';
  GRANT ALL PRIVILEGES ON ${KEYCLOAK_DB_NAME}.* TO '${KEYCLOAK_DB_USER}'@'%';

  # apply grants
  FLUSH PRIVILEGES;
EOF
